/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import code.HRM_T;
import code.HRA_T;
import inf.HRM;

/**
 *
 * @author dinet
 */
public class HRA extends javax.swing.JFrame {

    /**
     * Creates new form HRM
     */
    public HRA() {
        initComponents();
        HRM_T dataload = new HRM_T();
        dataload.empTableLoad(table6);
        dataload.depTableLoead(table3);
        dataload.designTableLoead(table4);
        HRA_T HRM = new HRA_T();
        HRM.showAssistant(table7);
    }
    
    public void userNameDisplay(String username){
        display_Name_Box.setText(username);
    }
    
    public void dataLoad(){
        int r = table6.getSelectedRow();
        String id = table6.getValueAt(r, 0).toString();
        String name = table6.getValueAt(r, 1).toString();
        String gender = table6.getValueAt(r, 2).toString();
        String epf_num = table6.getValueAt(r, 3).toString();
        String emp_design = table6.getValueAt(r, 4).toString();
        String emp_dep = table6.getValueAt(r, 5).toString();
        
        id_Box.setText(id);
        emp_Name_Box.setText(name);
        if(gender.equals("male")){
            male_Btn.setSelected(true);
        }else if(gender.equals("female")){
            female_Btn.setSelected(true);
        }else{
            male_Btn.setSelected(false);
            female_Btn.setSelected(false);
        }
        emp_D_Box.setText(emp_design);
        emp_Dep_Box.setText(emp_dep);
        emp_Epf_Box.setText(epf_num);
        
    }
    
    public void depboxload(){
        int r = table3.getSelectedRow();
        String dep_Id = table3.getValueAt(r, 0).toString();
        String dep_name = table3.getValueAt(r, 1).toString();
        
        dep_Id_Box.setText(dep_Id);
        dep_Name_Box.setText(dep_name);
    }
    
    public void designload(){
        int r = table4.getSelectedRow();
        String design_id = table4.getValueAt(r, 0).toString();
        String design_name = table4.getValueAt(r, 1).toString();
        
        design_Id_Box.setText(design_id);
        design_Name_Box.setText(design_name);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emp_Name_Box = new javax.swing.JTextField();
        emp_Epf_Box = new javax.swing.JTextField();
        male_Btn = new javax.swing.JRadioButton();
        female_Btn = new javax.swing.JRadioButton();
        update_Emp_Btn = new javax.swing.JButton();
        add_Emp_Btn = new javax.swing.JButton();
        add_Dep_Btn = new javax.swing.JButton();
        emp_Dep_Box = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emp_D_Box = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        delate_Emp_Btn = new javax.swing.JButton();
        id_Box = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        search_Box = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table6 = new javax.swing.JTable();
        Id_btn = new javax.swing.JRadioButton();
        design_btn = new javax.swing.JRadioButton();
        epf_btn = new javax.swing.JRadioButton();
        dep_btn = new javax.swing.JRadioButton();
        name_btn = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dep_Id_Box = new javax.swing.JLabel();
        dep_Name_Box = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        delate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        design_Id_Box = new javax.swing.JLabel();
        design_Name_Box = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table7 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        display_Name_Box2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        display_Name_Box = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Emp Name");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 89, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Gender");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 89, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Emp ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 89, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("EPF NO");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 89, 32));
        jPanel3.add(emp_Name_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 166, 41));
        jPanel3.add(emp_Epf_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 166, 41));

        male_Btn.setBackground(new java.awt.Color(51, 255, 204));
        buttonGroup1.add(male_Btn);
        male_Btn.setText("Male");
        jPanel3.add(male_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        female_Btn.setBackground(new java.awt.Color(51, 255, 204));
        buttonGroup1.add(female_Btn);
        female_Btn.setText("Female");
        jPanel3.add(female_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        update_Emp_Btn.setText("Update Employee");
        update_Emp_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_Emp_BtnActionPerformed(evt);
            }
        });
        jPanel3.add(update_Emp_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 39));

        add_Emp_Btn.setText("Add Employee");
        add_Emp_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_Emp_BtnActionPerformed(evt);
            }
        });
        jPanel3.add(add_Emp_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 130, 39));

        add_Dep_Btn.setText("Clear");
        add_Dep_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_Dep_BtnActionPerformed(evt);
            }
        });
        jPanel3.add(add_Dep_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 130, 39));
        jPanel3.add(emp_Dep_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 166, 41));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Emp Dep");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 32));
        jPanel3.add(emp_D_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 166, 41));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Emp Designation");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 32));

        delate_Emp_Btn.setText("Delate Employee");
        delate_Emp_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delate_Emp_BtnActionPerformed(evt);
            }
        });
        jPanel3.add(delate_Emp_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, 39));

        id_Box.setBackground(new java.awt.Color(153, 153, 153));
        id_Box.setText("ID Genarate By system");
        jPanel3.add(id_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, 40));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 539));

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        search_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_BoxActionPerformed(evt);
            }
        });
        search_Box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_BoxKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search_Box, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search_Box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 490, -1));

        table6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table6MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table6);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 121, 590, 400));

        Id_btn.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(Id_btn);
        Id_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Id_btn.setText("ID");
        jPanel4.add(Id_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 50, 30));

        design_btn.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(design_btn);
        design_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        design_btn.setText("Designation Name");
        jPanel4.add(design_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 30));

        epf_btn.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(epf_btn);
        epf_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        epf_btn.setText("EPF Number");
        jPanel4.add(epf_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 110, 30));

        dep_btn.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(dep_btn);
        dep_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dep_btn.setText("Department");
        dep_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dep_btnActionPerformed(evt);
            }
        });
        jPanel4.add(dep_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 110, 30));

        name_btn.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(name_btn);
        name_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        name_btn.setText("Name");
        jPanel4.add(name_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 80, 30));

        jTabbedPane1.addTab("ADD empolyee", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));

        jLabel5.setText("Department ID");

        jLabel9.setText("Department Name");

        dep_Id_Box.setText("Department ID");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Log Out");

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        delate.setText("Delate");
        delate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(dep_Id_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dep_Name_Box)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jButton2))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(delate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dep_Id_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dep_Name_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(delate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(34, 34, 34))
        );

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table3);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 580, 460));

        jTabbedPane1.addTab("Add Department", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(102, 255, 102));

        jLabel11.setText("Designation ID");

        jLabel12.setText("Designation Name");

        design_Id_Box.setText("Designation ID");

        jButton6.setText("ADD");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Delate");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(design_Name_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(design_Id_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(design_Id_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(design_Name_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table4MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table4);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 560, 290));

        jTabbedPane1.addTab("Add Designation ", jPanel6);

        table7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(table7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Show HR Assistant", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 60, 930, 500));

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("HR Assistance PAGE");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 330, 42));

        display_Name_Box2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        display_Name_Box2.setForeground(new java.awt.Color(255, 255, 255));
        display_Name_Box2.setText("Welcome Back!");
        jPanel7.add(display_Name_Box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 130, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 40, 40));

        display_Name_Box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        display_Name_Box.setText("username");
        jPanel7.add(display_Name_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 80, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    
    HRM_T dataload = new HRM_T();
    private void update_Emp_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_Emp_BtnActionPerformed
        int id = Integer.parseInt(id_Box.getText());
        String name = emp_Name_Box.getText();
        String gender;
        if(male_Btn.isSelected()){
            gender = "male";
        }else if(female_Btn.isSelected()){
            gender = "female";
        }else{
            gender = null;
        }
        int epf_number = Integer.parseInt(emp_Epf_Box.getText());
        String emp_dep = emp_Dep_Box.getText();
        String emp_design = emp_D_Box.getText();

        HRM_T up = new HRM_T();
        up.update(id, name, gender, epf_number, emp_design, emp_dep, table6);
    }//GEN-LAST:event_update_Emp_BtnActionPerformed

    private void add_Emp_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_Emp_BtnActionPerformed
        String name = emp_Name_Box.getText();
        String gender;
        if(male_Btn.isSelected()){
            gender = "male";
        }else if(female_Btn.isSelected()){
            gender = "female";
        }else{
            gender = null;
        }
        int epf_number;
        if(emp_Epf_Box.getText().equals("")){
            epf_number = 0;
        }else{
            epf_number = Integer.parseInt(emp_Epf_Box.getText());
        }
        String emp_dep = emp_Dep_Box.getText();
        String emp_design = emp_D_Box.getText();

        HRM_T add = new HRM_T();
        add.addEmployee(name, gender, epf_number, emp_design, emp_dep,table6);
        cleardata();
        dataload.empTableLoad(table6);

    }//GEN-LAST:event_add_Emp_BtnActionPerformed

    private void delate_Emp_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delate_Emp_BtnActionPerformed
        // TODO add your handling code here:
        String empid = id_Box.getText();
        HRM_T dele = new HRM_T();
        dele.userDelate(empid);
        cleardata();
        dele.empTableLoad(table6);
       
    }//GEN-LAST:event_delate_Emp_BtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login log = new login();
        log.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void search_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_BoxActionPerformed

    private void search_BoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_BoxKeyReleased
        String search = search_Box.getText();
        HRM_T sear = new HRM_T();
        sear.searchEmpolyees(search, table6 ,Id_btn,design_btn,epf_btn,dep_btn,name_btn);
    }//GEN-LAST:event_search_BoxKeyReleased
    
    HRM HRA_Data = new HRM();
    
    private void table6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table6MouseClicked
        // TODO add your handling code here:
        dataLoad();
    }//GEN-LAST:event_table6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dep_name = dep_Name_Box.getText();
        HRM_T dep = new HRM_T();
        dep.addDepartment(dep_name);
        dep.depTableLoead(table3);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int dep_Id = Integer.parseInt(dep_Id_Box.getText());
        String dep_name = dep_Name_Box.getText();
        HRM_T up = new HRM_T();
        up.updateDep(dep_Id, dep_name);
        up.depTableLoead(table3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void delateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delateActionPerformed
        HRM_T del = new HRM_T();
        int dep_Id = Integer.parseInt(dep_Id_Box.getText());
        del.depDelate(dep_Id);
        del.depTableLoead(table3);
    }//GEN-LAST:event_delateActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
        depboxload();
    }//GEN-LAST:event_table3MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        String des_Name = design_Name_Box.getText();
        HRM_T ad = new  HRM_T();
        ad.addDesignation(des_Name);
        ad.designTableLoead(table4);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int design_id = Integer.parseInt(design_Id_Box.getText());
        String design_name = design_Name_Box.getText();
        HRM_T up = new HRM_T();
        up.updateDesign(design_id, design_name);
        up.designTableLoead(table4);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int design_id = Integer.parseInt(design_Id_Box.getText());
        HRM_T del = new HRM_T();
        del.designDelate(design_id);
        del.designTableLoead(table4);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void table4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table4MouseClicked
        // TODO add your handling code here:
        designload();
    }//GEN-LAST:event_table4MouseClicked

    private void dep_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dep_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dep_btnActionPerformed

    private void add_Dep_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_Dep_BtnActionPerformed
       cleardata();
    }//GEN-LAST:event_add_Dep_BtnActionPerformed
    private void cleardata(){
       emp_Name_Box.setText("");
       emp_Dep_Box.setText("");
       emp_Epf_Box.setText("");
       id_Box.setText("Id genarate by system");
       emp_D_Box.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Id_btn;
    private javax.swing.JButton add_Dep_Btn;
    private javax.swing.JButton add_Emp_Btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton delate;
    private javax.swing.JButton delate_Emp_Btn;
    private javax.swing.JLabel dep_Id_Box;
    private javax.swing.JTextField dep_Name_Box;
    private javax.swing.JRadioButton dep_btn;
    private javax.swing.JLabel design_Id_Box;
    private javax.swing.JTextField design_Name_Box;
    private javax.swing.JRadioButton design_btn;
    private javax.swing.JLabel display_Name_Box;
    private javax.swing.JLabel display_Name_Box2;
    private javax.swing.JTextField emp_D_Box;
    private javax.swing.JTextField emp_Dep_Box;
    private javax.swing.JTextField emp_Epf_Box;
    private javax.swing.JTextField emp_Name_Box;
    private javax.swing.JRadioButton epf_btn;
    private javax.swing.JRadioButton female_Btn;
    private javax.swing.JLabel id_Box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton male_Btn;
    private javax.swing.JRadioButton name_btn;
    private javax.swing.JTextField search_Box;
    private javax.swing.JTable table3;
    private javax.swing.JTable table4;
    private javax.swing.JTable table6;
    private javax.swing.JTable table7;
    private javax.swing.JButton update_Emp_Btn;
    // End of variables declaration//GEN-END:variables
}
